### Get all users
GET http://localhost:3000/users

### Get a user
GET http://localhost:3000/users/696b094ac238aa46678cd18f

### Create a contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "email": "test5@example.com",
  "username": "test5@test.com",
  "name": "Hello4",
  "ipaddress": "94.121.163.63"
}

### PUT a contact
PUT http://localhost:3000/users/696b094ac238aa46678cd18f HTTP/1.1
content-type: application/json

{
  "email": "test@example.com",
  "username": "test@test.com",
  "name": "Hello",
  "ipaddress": "94.121.163.63"
}

### DELETE a contact
DELETE http://localhost:3000/users/6973e77ac17a81f885417b85 HTTP/1.1